namespace Digimon_Project.Enums
{
    public enum NPCMap : int
    {
        NPC_TOY_TOWN_PATAMON = 0xF031,
        NPC_TOY_TOWN_YUKIMIMON = 0xF043,
        NPC_TOY_TOWN_MOTIMON = 0x0072,
        NPC_TOY_TOWN_YOKOMON = 0xF0A7,
        NPC_TOY_TOWN_TSUNOMON = 0x0096,
        NPC_TOY_TOWN_ELECMON = 0xF16F,
        NPC_HAPPYPRK_ITEM_SHOP = 0x13ED,
        NPC_HAPPYPRK_CARD_SHOP = 0x1451,
        NPC_HAPPYPRK_PRINCEMAMON = 0x13BA,
        NPC_MUDVILLAGE_ITEM_SHOP = 0x4E85,
        NPC_MUDVILLAGE_CARD_SHOP = 0x4EE9,
        NPC_GEKOSWAMP_ITEM_SHOP = 0x9CA5,
        NPC_GEKOSWAMP_CARD_SHOP = 0x9D09,
        NPC_TIMEVLG_ITEM_SHOP = 0xEAC5,
        NPC_TIMEVLG_CARD_SHOP = 0xEB29,
        NPC_BABALAND_CARD_SHOP = 0x011239,
        NPC_BABALAND_ITEM_SHOP = 0x0111D5,
        NPC_KATE = 0x012C,
        //NPC_BUFF_DAY = 0x012C,
    }
}
